// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: api/notes/service.proto

package notes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_notes_service_proto protoreflect.FileDescriptor

const file_api_notes_service_proto_rawDesc = "" +
	"\n" +
	"\x17api/notes/service.proto\x12\x1fgithub.com.structxz.grpc_simple\x1a\x18api/notes/messages.proto2\xf7\x01\n" +
	"\fNotesService\x12q\n" +
	"\bSaveNote\x120.github.com.structxz.grpc_simple.SaveNoteRequest\x1a1.github.com.structxz.grpc_simple.SaveNoteResponse\"\x00\x12t\n" +
	"\tListNotes\x121.github.com.structxz.grpc_simple.ListNotesRequest\x1a2.github.com.structxz.grpc_simple.ListNotesResponse\"\x00B5Z3github.com/structxz/grpc_simple/pkg/api/notes;notesb\x06proto3"

var file_api_notes_service_proto_goTypes = []any{
	(*SaveNoteRequest)(nil),   // 0: github.com.structxz.grpc_simple.SaveNoteRequest
	(*ListNotesRequest)(nil),  // 1: github.com.structxz.grpc_simple.ListNotesRequest
	(*SaveNoteResponse)(nil),  // 2: github.com.structxz.grpc_simple.SaveNoteResponse
	(*ListNotesResponse)(nil), // 3: github.com.structxz.grpc_simple.ListNotesResponse
}
var file_api_notes_service_proto_depIdxs = []int32{
	0, // 0: github.com.structxz.grpc_simple.NotesService.SaveNote:input_type -> github.com.structxz.grpc_simple.SaveNoteRequest
	1, // 1: github.com.structxz.grpc_simple.NotesService.ListNotes:input_type -> github.com.structxz.grpc_simple.ListNotesRequest
	2, // 2: github.com.structxz.grpc_simple.NotesService.SaveNote:output_type -> github.com.structxz.grpc_simple.SaveNoteResponse
	3, // 3: github.com.structxz.grpc_simple.NotesService.ListNotes:output_type -> github.com.structxz.grpc_simple.ListNotesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_notes_service_proto_init() }
func file_api_notes_service_proto_init() {
	if File_api_notes_service_proto != nil {
		return
	}
	file_api_notes_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_service_proto_rawDesc), len(file_api_notes_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_service_proto_goTypes,
		DependencyIndexes: file_api_notes_service_proto_depIdxs,
	}.Build()
	File_api_notes_service_proto = out.File
	file_api_notes_service_proto_goTypes = nil
	file_api_notes_service_proto_depIdxs = nil
}
